language: cpp

dist: trusty

before_script:
  - sudo apt-get update
  - sudo apt-get install cmake g++-multilib libc6-dev-i386 gcc-arm-none-eabi libnewlib-arm-none-eabi

script:
  - cmake -H. -Bbuild -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=../toolchain-gcc-arm-none-eabi.cmake
  - cmake -C build
